#!/usr/local/bin/perl -w -CSAD

use strict;

use DBI;
my $dbh = DBI->connect(
	"dbi:SQLite:dbname=plz.sqlite3", "", "",
	{
	  RaiseError     => 1,
	  sqlite_unicode => 1,
	}
);

{
    my $sth = $dbh->table_info(undef, undef, "PLZ", 'TABLE');
    $sth->execute;
    my @info = $sth->fetchrow_array;
    my $exists = scalar @info;
    if ($exists ==0){
	my $stmt = qq(CREATE TABLE PLZ
		(PLZ   TEXT    NOT NULL,
		 ORT   TEXT    NOT NULL););
	my $rv = $dbh->do($stmt);
	if($rv < 0){
	    print $DBI::errstr;
	} else {
	    print "Table created successfully\n";
	}
    }
}

my $stmt = qq(INSERT INTO PLZ (PLZ,ORT) VALUES (?,?));
my $sth = $dbh->prepare($stmt) or die $DBI::errstr;

open(FILE,"<DE.tab");
my $head=<FILE>;
$dbh->begin_work;

while (<FILE>){
	chomp;
	s/\r//g;
	my @a=split(/\t/);
	next if $a[7] eq "";
	my $ort=$a[3];
	next if $ort eq "";
	my @plz=split(/,/,$a[7]);
	for my $plz (@plz){
#		print "$ort -> $plz\n";
		my $rv = $sth->execute($plz,$ort) or die $DBI::errstr;
		if($rv < 0){
			print $DBI::errstr;
		}
	}
}
close(FILE);

$dbh->commit;
$dbh->disconnect();

