#!/bin/sh
#Text Formatting#
errors='*Error:*'
privileges='*Privileges:*'
#################

echo "*-- Universal tool for everything --*"

if [ -z "$1" ] ; then
    echo "Active commands:"
    cd ..
    for a in */run ; do 
	echo -n "${a%/run}\n "
    done
    echo
    exit 0
fi
if [ ! -d "../$1" ] ; then
    echo "$errors Unknown command $1"
    exit 0
fi

if [ ! -f "../$1/help" ] ; then
    echo "$errors No help  available for $1"
    exit 0
fi

cat "../$1/help"
