#!/usr/local/bin/perl -w -CSAD

use strict;
use DBI;

my $dbh = DBI->connect(
        "dbi:SQLite:dbname=kfz.sqlite3", "", "",
        {
          RaiseError     => 1,
          sqlite_unicode => 1,
#         AutoCommit     => 1,
        }
);

{
    my $sth = $dbh->table_info(undef, undef, "KFZ", 'TABLE');
    $sth->execute;
    my @info = $sth->fetchrow_array;
    my $exists = scalar @info;
    if ($exists ==0){
        my $stmt = qq(CREATE TABLE KFZ
                (KFZ   TEXT    NOT NULL,
                 ORT   TEXT    NOT NULL,
                 INFO  TEXT););
        my $rv = $dbh->do($stmt);
        if($rv < 0){
            print $DBI::errstr;
        } else {
            print "Table created successfully\n";
        }
    }
}

my $stmt = qq(INSERT INTO KFZ (KFZ,ORT) VALUES (?,?));
my $sth = $dbh->prepare($stmt) or die $DBI::errstr;

use HTML::TableExtract;
#my $te = HTML::TableExtract->new( headers => ["Abk.","Stadt/Landkreis","abgeleitet von"] );
my $te = HTML::TableExtract->new( headers => ["Abk.","abgeleitet von"] );
open (F,"<Liste_der_Kfz-Kennzeichen_in_Deutschland") || die;
my $html_string=join("",<F>);
close(F);
$te->parse($html_string);

$dbh->begin_work;

# Examine all matching tables
foreach my $ts ($te->tables) {
    print "Table (", join(',', $ts->coords), "):\n";
    foreach my $row ($ts->rows) {
        next if !defined $row->[0];
        $row->[1]="Internationale Hauptquartiere (NATO)" if $row->[0] eq "X";
        $row->[1]="Bundeswehr" if $row->[0] eq "Y";
        my $rv = $sth->execute(@$row) or die $DBI::errstr;
        if($rv < 0){
            print $DBI::errstr;
        }
    }
}
$dbh->commit;
$dbh->disconnect();
